resources:
  
  - name: windows-stemcell-builder-repo
    type: git
    source:
      uri: https://github.com/patrickhuber/windows-stemcell-builder.git

  - name: windows-stemcell-builder-runtime
    type: docker-image
    source:
      repository: patrickhuber/windows-stemcell-builder-runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:

  - name: runtime
    plan: 
    - get: windows-stemcell-builder-repo
    - put: windows-stemcell-builder-runtime
      params:
        build: windows-stemcell-builder-repo
        dockerfile: windows-stemcell-builder-repo/Dockerfile

  - name: iso
    plan:  
    - get: windows-stemcell-builder-repo      
    - task: ensure-iso
      image: windows-stemcell-builder-runtime
      file: windows-stemcell-builder-repo/ensure-iso.yml
  
  - name: vmx
    plan:
    - get: windows-stemcell-builder-repo
    - task: run-image-build
      image: windows-stemcell-builder-runtime
      file: windows-stemcell-builder-repo/ensure-vmx.yml    