resources:
  
  - name: windows-stemcell-builder-repo
    type: git
    source:
      uri: https://github.com/patrickhuber/windows-stemcell-builder.git

  - name: windows-stemcell-builder-runtime
    type: docker-image
    source:
      repository: patrickhuber/windows-stemcell-builder-runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:

  - name: runtime
    plan: 
    - get: windows-stemcell-builder-repo
    - put: windows-stemcell-builder-runtime
      params:
        build: windows-stemcell-builder-repo
        dockerfile: windows-stemcell-builder-repo/Dockerfile

  - name: iso
    plan:  
    - get: windows-stemcell-builder-repo      
    - task: ensure-iso
      image: windows-stemcell-builder-runtime
      file: windows-stemcell-builder-repo/ensure-iso.yml
      params:
        GOVC_URL: {{vcenter_ip}}
        GOVC_PASSWORD: {{vcenter_password}}
        GOVC_USERNAME: {{vcenter_username}}
        GOVC_INSECURE: true
        GOVC_DATACENTER: {{vcenter_datacenter}}
        GOVC_DATASTORE: {{vcenter_datastore}}
        GOVC_NETWORK: {{vcenter_network}}
        GOVC_CLUSTER: {{vcenter_cluster}}
        iso: https://care.dlservice.microsoft.com/dl/download/1/4/9/149D5452-9B29-4274-B6B3-5361DBDA30BC/14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO
        iso_name: windows-server-2016-x64-evaluation-en-us.iso
        iso_folder: {{vcenter_iso_folder}}  
  
  - name: vmx
    plan:
    - get: windows-stemcell-builder-repo
    - task: run-image-build
      image: windows-stemcell-builder-runtime
      file: windows-stemcell-builder-repo/ensure-vmx.yml    