resources:
  
  - name: govmomi
    type: git
    source:
      uri: https://github.com/vmware/govmomi.git

  - name: govmomi-runtime
    type: docker-image
    source:
      repository: patrickhuber/govmomi-runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}
      
jobs:
  - name: vmx
    plan:
    - get: govmomi
      
    